#!/usr/bin/python

import requests
import json
import argparse

parser = argparse.ArgumentParser(description='Python program to export wallabag articles')
parser.add_argument('url',help='URL of wallabag')
parser.add_argument('client_id',help='')
parser.add_argument('client_secret',help='')
parser.add_argument('username','-u',help='Username of the account')
parser.add_argument('password','-p',help='Password of the account')

args = parser.args_parse()
url = args.url
client_id = args.client_id
client_secret = args.client_secret
username = args.username
password = args.password

def get_token(url,client_id,client_secret,username,password):
    r = requests.get('
